//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _200x200 {
            get {
                object obj = ResourceManager.GetObject("_200x200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _750x115 {
            get {
                object obj = ResourceManager.GetObject("_750x115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;h1&gt;Welcome to the Joinup Page Layour Creator!&lt;/h1&gt;
        ///
        ///&lt;p&gt;Text goes here...&lt;/p&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;img alt=&quot;Banner&quot; data-entity-type=&quot;file&quot; data-entity-uuid=&quot;4a35c794-254c-449e-b5e9-9c5b349b4247&quot; data-image-style=&quot;&quot; src=&quot;https://joinup.ec.europa.eu/sites/default/files/inline-images/1000x115-1.png&quot; /&gt;&lt;/p&gt;
        ///
        ///&lt;h2&gt;Lorem ipsum dolor sit amet&lt;/h2&gt;
        ///
        ///&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_1_HTML {
            get {
                return ResourceManager.GetString("Template_1_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;img alt=&quot;Banner&quot; data-entity-type=&quot;file&quot; data-entity-uuid=&quot;4a35c794-254c-449e-b5e9-9c5b349b4247&quot; data-image-style=&quot;&quot; src=&quot;https://joinup.ec.europa.eu/sites/default/files/inline-images/1000x115-1.png&quot; /&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;img alt=&quot;Image&quot; data-align=&quot;left&quot; data-entity-type=&quot;file&quot; data-entity-uuid=&quot;835942f8-dc96-490d-879f-9bbd6f88a6ce&quot; data-image-style=&quot;&quot; src=&quot;https://joinup.ec.europa.eu/sites/default/files/inline-images/200x200-1.png&quot; align=&quot;left&quot; /&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_2_HTML {
            get {
                return ResourceManager.GetString("Template_2_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;img alt=&quot;Banner&quot; data-entity-type=&quot;file&quot; data-entity-uuid=&quot;4a35c794-254c-449e-b5e9-9c5b349b4247&quot; data-image-style=&quot;&quot; src=&quot;https://joinup.ec.europa.eu/sites/default/files/inline-images/1000x115-1.png&quot; /&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_3_HTML {
            get {
                return ResourceManager.GetString("Template_3_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;img alt=&quot;Image&quot; data-align=&quot;left&quot; data-entity-type=&quot;file&quot; data-entity-uuid=&quot;835942f8-dc96-490d-879f-9bbd6f88a6ce&quot; data-image-style=&quot;&quot; src=&quot;https://joinup.ec.europa.eu/sites/default/files/inline-images/200x200-1.png&quot; align=&quot;left&quot;/&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehende [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_4_HTML {
            get {
                return ResourceManager.GetString("Template_4_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;img alt=&quot;Banner&quot; data-entity-type=&quot;file&quot; data-entity-uuid=&quot;4a35c794-254c-449e-b5e9-9c5b349b4247&quot; data-image-style=&quot;&quot; src=&quot;https://joinup.ec.europa.eu/sites/default/files/inline-images/1000x115-1.png&quot; /&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_5_HTML {
            get {
                return ResourceManager.GetString("Template_5_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&lt;/p&gt;
        ///
        ///&lt;table&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;
        ///			&lt;p&gt;&lt;img alt=&quot;IMG&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_6_HTML {
            get {
                return ResourceManager.GetString("Template_6_HTML", resourceCulture);
            }
        }
    }
}
